#https://github.com/prof18/feed-flow/blob/main/.github/workflows/code-checks.yaml
name: Code Checks
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  checks:
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-gradle
        with:
          gradle-cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

      - name: Install Swift Lint
        run: |
          brew install swiftlint

      - name: Run Swift Lint
        run: |
          cd ios
          /opt/homebrew/bin/swiftlint
          cd ..

      - name: Run Checks
        run: ./gradlew check

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            **/build/reports/*    

  build-android-app:
    name: Build Android App
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-gradle

      - name: Build Android Sample
        run: ./gradlew :androidApp:assembleGooglePlayDebug

  build-ios-app:
    name: Build iOS App
    runs-on: macos-14
    needs: [ checks ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Xcode version
        run: |
          /usr/bin/xcodebuild -version   

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Xcode version
        run: |
          /usr/bin/xcodebuild -version 

      - name: Setup environment
        uses: ./.github/actions/setup-gradle

      - name: Build iOS Sample
        run: |
          cd ios
          xcodebuild -configuration Debug -scheme ios -sdk iphoneos -destination name='iPhone 16 Pro' build | xcbeautify --renderer github-actions